# Splitting Columns in Pandas

This notebook demonstrates techniques for splitting a single DataFrame column into multiple columns.

## Topics Covered

- Splitting string columns
- Using `str.split()`
- Separating values into multiple columns
- Handling structured string data
- Converting split values into DataFrame columns

## Goal

The goal is to learn how to transform columns containing multiple pieces of information into structured DataFrame columns.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Split Columns

In [2]:
df = pd.DataFrame({'Name' : ['mahdi ghorbani' , 'MAHDI GHORBANI'] , 'Location' : ['iran' , 'iran']})
df

             Name Location
0  mahdi ghorbani     iran
1  MAHDI GHORBANI     iran

In [7]:
df[['Firstname' , 'Lastname']] = df.Name.str.split(' ' , expand=True)
df

             Name Location Firstname  Lastname
0  mahdi ghorbani     iran     mahdi  ghorbani
1  MAHDI GHORBANI     iran     MAHDI  GHORBANI

In [14]:
df

             Name Location Firstname  Lastname
0  mahdi ghorbani     iran     mahdi  ghorbani
1  MAHDI GHORBANI     iran     MAHDI  GHORBANI

In [15]:
df['Firstname'] , df['Lastname'] = zip(*df.Name.str.split(' '))

In [16]:
df

             Name Location Firstname  Lastname
0  mahdi ghorbani     iran     mahdi  ghorbani
1  MAHDI GHORBANI     iran     MAHDI  GHORBANI