# Selecting Columns in Pandas

This notebook demonstrates different techniques for selecting columns from a Pandas DataFrame.

## Topics Covered

- Selecting individual columns
- Selecting multiple columns
- Selecting columns by data type
- Using `select_dtypes()`
- Working with numeric and non-numeric columns

## Goal

The goal is to learn how to efficiently select and work with specific columns in a DataFrame.

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('../data/Churn_Modelling.csv')
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [3]:
df.dtypes

RowNumber            int64
CustomerId           int64
Surname             object
CreditScore          int64
Geography           object
Gender              object
Age                  int64
Tenure               int64
Balance            float64
NumOfProducts        int64
HasCrCard            int64
IsActiveMember       int64
EstimatedSalary    float64
Exited               int64
dtype: object

In [4]:
len(df.dtypes)

14

In [5]:
len(df.select_dtypes(include='int64').columns)

9

In [6]:
len(df.select_dtypes(exclude='int64').columns)

5

In [7]:
df.select_dtypes(include='object').head(4)

    Surname Geography  Gender
0  Hargrave    France  Female
1      Hill     Spain  Female
2      Onio    France  Female
3      Boni    France  Female